"use client";
import {useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {FeatureIcon,featureIconOptions} from "@/components/feature-icon";
type Any=Record<string,any>;
type IncludedItem={title:string;description:string;icon:string;visible:boolean};

export function Login(){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const router=useRouter();return <form className="cms-form" onSubmit={async e=>{e.preventDefault();const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})});if(r.ok){router.push("/admin/dashboard");router.refresh()}else setError("Invalid email or password")}}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="cms-error">{error}</p>}<button className="button">Sign in</button></form>}

const emptyService={name:"",slug:"",categoryLabel:"SPECIALIST SERVICE",heroHeading:"",heroDescription:"",heroImage:"",primaryButtonText:"Book Consultation",primaryButtonLink:"/booking",secondaryButtonText:"",secondaryButtonLink:"",trustPoints:[],overviewHeading:"Service overview",overviewContent:"Professional support tailored to your goals.",targetAudience:[],includedFeatures:[],priceAmount:"",priceMode:"STARTING_FROM",priceCurrency:"TZS",priceVisible:true,priceNote:"",externalCostsIncluded:null,processSteps:[],benefits:[],faqs:[],relatedServiceIds:[],finalCtaHeading:"Ready to Discuss Your Project?",finalCtaDescription:"Book a consultation with our team to discuss your goals and find the right solution for your business.",seoTitle:"",seoDescription:"",openGraphImage:"",status:"DRAFT",active:true,displayOrder:0};
const fields=[["name","Service name"],["slug","URL slug"],["categoryLabel","Small category label"],["heroHeading","Service title"],["heroDescription","Short service description"],["finalCtaHeading","Consultation heading"],["finalCtaDescription","Consultation description"],["primaryButtonText","Consultation button text"],["seoTitle","SEO title"],["seoDescription","SEO description"]];
const normalizeIncluded=(value:unknown):IncludedItem[]=>(Array.isArray(value)?value:[]).map((x,i)=>typeof x==="string"?{title:x,description:"Professional support tailored to the client’s goals.",icon:featureIconOptions[i%featureIconOptions.length],visible:true}:{title:x?.title||"",description:x?.description||"",icon:x?.icon||"check",visible:x?.visible!==false});

export function ServicesEditor(){
  const[items,setItems]=useState<Any[]>([]),[item,setItem]=useState<Any>(emptyService),[busy,setBusy]=useState(true),[msg,setMsg]=useState(""),[dragIndex,setDragIndex]=useState<number|null>(null);
  const editorRef=useRef<HTMLElement>(null);
  const load=()=>fetch("/api/admin/services").then(r=>r.json()).then(x=>{setItems(x);setBusy(false)});
  useEffect(()=>{load()},[]);
  const included=normalizeIncluded(item.includedFeatures);
  const setIncluded=(next:IncludedItem[])=>setItem({...item,includedFeatures:next});
  async function save(){setBusy(true);setMsg("");const payload={...item,includedFeatures:included,displayOrder:Number(item.displayOrder)};const r=await fetch(`/api/admin/services${item.id?"/"+item.id:""}`,{method:item.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});setBusy(false);if(r.ok){setMsg("Service and included items saved successfully.");setItem(emptyService);load()}else{const result=await r.json().catch(()=>({}));setMsg(result.error||"Please check all required fields.")}}
  async function remove(id:string){if(!confirm("Delete this service permanently?"))return;await fetch("/api/admin/services/"+id,{method:"DELETE"});load()}
  async function move(i:number,d:number){const copy=[...items],target=i+d;if(target<0||target>=copy.length)return;[copy[i],copy[target]]=[copy[target],copy[i]];setItems(copy);await fetch("/api/admin/services",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({order:copy.map(x=>x.id)})})}
  function updateIncluded(index:number,patch:Partial<IncludedItem>){setIncluded(included.map((x,i)=>i===index?{...x,...patch}:x))}
  function dropIncluded(target:number){if(dragIndex===null||dragIndex===target)return;const next=[...included];const[moved]=next.splice(dragIndex,1);next.splice(target,0,moved);setIncluded(next);setDragIndex(null)}
  function editService(service:Any){setItem({...service,includedFeatures:normalizeIncluded(service.includedFeatures)});setMsg("");requestAnimationFrame(()=>editorRef.current?.scrollIntoView({behavior:"smooth",block:"start"}))}
  return <div className="cms-grid">
    <section><div className="cms-heading"><h2>Services</h2><button onClick={()=>{setItem(emptyService);requestAnimationFrame(()=>editorRef.current?.scrollIntoView({behavior:"smooth"}))}}>+ New</button></div>{busy&&<p>Loading…</p>}{items.map((x,i)=><div className="cms-row" key={x.id}><span><b>{x.name}</b><small>{x.status} · {x.active?"Active":"Inactive"} · {normalizeIncluded(x.includedFeatures).length} included</small></span><span><button onClick={()=>move(i,-1)}>↑</button><button onClick={()=>move(i,1)}>↓</button><a href={`/services/${x.slug}`} target="_blank">Preview</a><button className="edit-button" onClick={()=>editService(x)}>Edit</button><button onClick={()=>remove(x.id)}>Delete</button></span></div>)}</section>
    <section className="cms-form" ref={editorRef}><div className="cms-heading"><h2>{item.id?`Edit: ${item.name}`:"Create Service"}</h2>{item.slug&&<a href={`/services/${item.slug}`} target="_blank">Open live page ↗</a>}</div><p className="cms-help">Edit the public title, description, price, checklist and consultation section below.</p>
      {fields.map(([key,label])=><label key={key}>{label}{key.toLowerCase().includes("image")?<ImageField value={item[key]||""} onChange={v=>setItem({...item,[key]:v})}/>:key.includes("Description")||key.includes("Content")?<textarea value={item[key]||""} onChange={e=>setItem({...item,[key]:e.target.value})}/>:<input value={item[key]||""} onChange={e=>setItem({...item,[key]:e.target.value})}/>}</label>)}
      <div className="pricing-admin"><div className="cms-heading"><span><b>Service Price</b><small>One clear price is displayed below the service description.</small></span><label className="cms-check"><input type="checkbox" checked={item.priceVisible!==false} onChange={e=>setItem({...item,priceVisible:e.target.checked})}/> Show price</label></div><div className="cms-three"><label>Price type<select value={item.priceMode||"STARTING_FROM"} onChange={e=>setItem({...item,priceMode:e.target.value})}><option value="STARTING_FROM">Starting from</option><option value="FIXED">Fixed price</option></select></label><label>Currency<select value={item.priceCurrency||"TZS"} onChange={e=>setItem({...item,priceCurrency:e.target.value})}><option value="TZS">TZS</option><option value="USD">USD</option></select></label><label>Amount<input inputMode="numeric" placeholder="150000" value={item.priceAmount||""} onChange={e=>setItem({...item,priceAmount:e.target.value.replace(/[^0-9.]/g,"")})}/></label></div><label>Short pricing note<textarea rows={2} placeholder="Optional note about scope or billing" value={item.priceNote||""} onChange={e=>setItem({...item,priceNote:e.target.value})}/></label><label>External costs<select value={item.externalCostsIncluded===true?"included":item.externalCostsIncluded===false?"excluded":"unspecified"} onChange={e=>setItem({...item,externalCostsIncluded:e.target.value==="included"?true:e.target.value==="excluded"?false:null})}><option value="excluded">Not included</option><option value="included">Included</option><option value="unspecified">Do not display a note</option></select></label></div>
      <div className="included-admin"><div className="cms-heading"><span><b>What&apos;s Included</b><small> Drag cards to reorder. Changes appear in the preview below.</small></span><button onClick={()=>setIncluded([...included,{title:"New included item",description:"Describe the professional deliverable included with this service.",icon:"check",visible:true}])}>+ Add item</button></div>
        <div className="included-admin-list">{included.map((feature,index)=><div className={`included-admin-item ${feature.visible?"":"is-hidden"}`} draggable onDragStart={()=>setDragIndex(index)} onDragOver={e=>e.preventDefault()} onDrop={()=>dropIncluded(index)} key={index}>
          <span className="drag-handle" title="Drag to reorder">⋮⋮</span><span className="admin-feature-icon"><FeatureIcon name={feature.icon}/></span><div><input aria-label="Feature title" value={feature.title} onChange={e=>updateIncluded(index,{title:e.target.value})}/><textarea aria-label="Feature description" rows={2} value={feature.description} onChange={e=>updateIncluded(index,{description:e.target.value})}/><label>Icon<select value={feature.icon} onChange={e=>updateIncluded(index,{icon:e.target.value})}>{featureIconOptions.map(icon=><option key={icon} value={icon}>{icon}</option>)}</select></label></div><span className="included-actions"><button onClick={()=>updateIncluded(index,{visible:!feature.visible})}>{feature.visible?"Hide":"Show"}</button><button className="danger" onClick={()=>setIncluded(included.filter((_,i)=>i!==index))}>Remove</button></span>
        </div>)}</div>
        <div className="included-preview"><span className="preview-label">ADMIN PREVIEW · {included.filter(x=>x.visible).length} VISIBLE ITEMS</span><div className="included-preview-grid">{included.filter(x=>x.visible).map((x,i)=><article key={i}><FeatureIcon name={x.icon}/><small>{String(i+1).padStart(2,"0")}</small><b>{x.title}</b><p>{x.description}</p></article>)}</div></div>
      </div>
      <div className="cms-two"><label>Status<select value={item.status} onChange={e=>setItem({...item,status:e.target.value})}><option>DRAFT</option><option>PUBLISHED</option></select></label><label>Display order<input type="number" value={item.displayOrder} onChange={e=>setItem({...item,displayOrder:e.target.value})}/></label></div><label className="cms-check"><input type="checkbox" checked={item.active} onChange={e=>setItem({...item,active:e.target.checked})}/> Active</label>{msg&&<p className={msg.includes("successfully")?"cms-success":"cms-error"}>{msg}</p>}<button className="button" disabled={busy} onClick={save}>{busy?"Saving…":"Save Service"}</button>
    </section>
  </div>;
}

function ImageField({value,onChange}:{value:string;onChange:(v:string)=>void}){const[busy,setBusy]=useState(false);return <span className="cms-image"><input value={value} onChange={e=>onChange(e.target.value)} placeholder="Image URL"/><input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setBusy(true);const fd=new FormData();fd.append("file",f);const r=await fetch("/api/admin/upload",{method:"POST",body:fd});const d=await r.json();if(r.ok)onChange(d.url);setBusy(false)}}/>{busy&&<small>Uploading…</small>}</span>}

export function ContentEditor({type}:{type:string}){const[items,setItems]=useState<Any[]>([]);const[item,setItem]=useState<Any>({type,slug:"",title:"",summary:"",data:{},image:"",seoTitle:"",seoDescription:"",status:"DRAFT",displayOrder:0});const load=()=>fetch("/api/admin/content?type="+type).then(r=>r.json()).then(setItems);useEffect(()=>{load()},[type]);async function save(){const r=await fetch(`/api/admin/content${item.id?"/"+item.id:""}`,{method:item.id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...item,type,displayOrder:Number(item.displayOrder)})});if(r.ok){alert("Saved successfully");setItem({type,slug:"",title:"",summary:"",data:{},image:"",seoTitle:"",seoDescription:"",status:"DRAFT",displayOrder:0});load()}}return <div className="cms-grid"><section><h2>{type}</h2>{items.map(x=><div className="cms-row" key={x.id}><span><b>{x.title}</b><small>{x.status}</small></span><span><button onClick={()=>setItem(x)}>Edit</button><button onClick={async()=>{if(confirm("Delete this item?")){await fetch("/api/admin/content/"+x.id,{method:"DELETE"});load()}}}>Delete</button></span></div>)}</section><section className="cms-form"><h2>Edit {type}</h2>{["title","slug","summary","seoTitle","seoDescription"].map(k=><label key={k}>{k}<input value={item[k]||""} onChange={e=>setItem({...item,[k]:e.target.value})}/></label>)}<label>Image<ImageField value={item.image||""} onChange={v=>setItem({...item,image:v})}/></label><label>Content data (JSON)<textarea rows={12} value={typeof item.data==="string"?item.data:JSON.stringify(item.data,null,2)} onChange={e=>{try{setItem({...item,data:JSON.parse(e.target.value)})}catch{setItem({...item,data:e.target.value})}}}/></label><label>Status<select value={item.status} onChange={e=>setItem({...item,status:e.target.value})}><option>DRAFT</option><option>PUBLISHED</option></select></label><button className="button" onClick={save}>Save</button></section></div>}
